title: Erin Maier
url: "https://ermaier.github.io/"
baseurl: "/"

description: This is a Demo description and will be updated soon when the content is available

author:
  name: Erin Maier
  email: erinrmaier@email.arizona.edu
